name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 修复权限（仅当文件存在时执行）
      - name: Verify Frontend Files
        id: verify-frontend
        run: |
          if [ -f "stream-rec-frontend/package.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Fix File Permissions
        if: steps.verify-frontend.outputs.exists == 'true'
        run: chmod +x stream-rec-frontend/package.json

      # 设置 Java 环境
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'

      # 构建后端
      - name: Build Backend
        run: ./gradlew stream-rec:build -x test

      # 构建前端
      - name: Build Frontend
        run: npm ci && npm run build
        working-directory: ./stream-rec-frontend  # 关键！

      # 部署到服务器
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './dist/**'
          target: '/opt/stream-rec/'
          strip_components: 1
