
name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 推荐升级到v4版本

      # 修复权限问题（关键步骤！）
      - name: Fix File Permissions
        run: |
          chmod +x gradlew
          chmod +x stream-rec-frontend/package.json  # 确保前端脚本可执行

      # 设置Java环境（增加缓存优化）
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'  # 缓存Gradle依赖加速构建

      # 构建后端（增加日志输出）
      - name: Build Backend
        run: ./gradlew stream-rec:build -x test
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2048m"  # 防止OOM

      # 构建前端（修正路径问题）
      - name: Build Frontend
        run: |
          cd stream-rec-frontend
          npm ci --legacy-peer-deps  # 处理可能的依赖冲突
          npm run build
        working-directory: ./stream-rec-frontend  # 显式指定工作目录

      # 收集构建产物（关键修正）
      - name: Prepare Artifacts
        run: |
          mkdir -p ./dist/backend
          cp stream-rec/build/libs/stream-rec.jar ./dist/backend/
          cp -r stream-rec-frontend/dist/* ./dist/frontend/
          echo "Build artifacts prepared"

      # 部署到服务器（优化路径）
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './dist/**'  # 递归上传所有构建产物
          target: '/opt/stream-rec/'
          strip_components: 1  # 移除顶层dist目录
